name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v2

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: beta

    # Get flutter dependencies.
    - run: flutter pub get
    
    # Enable web
    - run: flutter config --enable-web

    # Build web
    - run: flutter build web
    
    # Build apk.
    - run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi

    #
    # Deploy to netlify
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './build/web'
        production-branch: master
        github-token: ${{ secrets.MY_GITHUB_SECRET }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1